name: flutter_intern_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  cloud_firestore: ^3.4.3
  firebase_auth: ^3.4.2
  flutter: 
    sdk: flutter
  firebase_core: ^1.20.0
   #for dynamic ui
  flutter_screenutil: ^5.3.1

  #for state management
  get: 4.6.5
  get_storage: ^2.0.3

  image_picker: ^0.8.5
  image_cropper: ^1.5.1

  #for date formatting
  intl: ^0.17.0

  octo_image: ^1.0.1
  internet_connection_checker: ^0.0.1+3
  google_fonts: ^3.0.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_rating_bar: ^4.0.1
  intl_phone_number_input:
  logger:
  pin_code_fields: ^7.4.0
  intl_phone_field: ^3.1.0
  carousel_slider: ^4.1.1



dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  fonts:
    - family: Varela Round     
      fonts:
        - asset: assets/fonts/ElMessiri-VariableFont_wght.ttf
  uses-material-design: true
